### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by mazh91** [JamesGardiner/chwrapper#27]
I'm getting the following error when trying to import the module. Please report to developers.
```
>>> import chwrapper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/milad/.local/lib/python2.7/site-packages/chwrapper/__init__.py", line 4, in <module>
    from chwrapper.services.base import Service
  File "/home/milad/.local/lib/python2.7/site-packages/chwrapper/services/base.py", line 50
    raise KeyError(msg) from e
                           ^
SyntaxError: invalid syntax
```
Update: this is a Python 2.7 issue. It works fine with Python 3.

**Comment by JamesGardiner** [comment]
@mazh91 - I'm not officially supporting any Python 2 versions with this package. I'd be more than happy to accept a pull request that gets this to work for your scenario, so long as changes required are minimal. I will add a supported version section to the README to make this clearer.
